package com.Argano.enums;

public enum ConfigProperties {

	OVERRIDEREPORTS, 
	BROWSER, 
	PASSEDSTEPSSCREENSHOTS, 
	FAILEDSTEPSSCREENSHOTS, 
	SKIPPEDSTEPSSCREENSHOTS,
	RETRYFAILEDTESTS, 
	SENDRESULTINMAIL,
	URL,
	TOEMAILRECIPIENT, 
	CCEMAILRECIPIENT, 
	BCCEMAILRECIPIENT;

}
